### ISSUE TITLE
Member einzeln anzeigen

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Crew#4]
Es wäre schön, wenn man die Members auch einzeln mit [pirate id=“1031″] anzeigen könnte. Einzeln geht momentan nur über den Umweg einer extra-Gruppe pro Member.

BTW: Bitte auf einen Begriff im Backend festlegen, man sieht groups, crew und team - etwas verwirrend

**Comment by xwolfde** [comment]
Jupp, an der Funktion bin ich noch bei. Wäre diesen Montag nicht eine andere Sache dazwischen gekommen...  :/

Steht bei mir in der Prio ganz oben.

**Comment by ukcb** [comment]
Ich sage schon mal danke! Schön wäre es, wenn man den Style ändern könnte. Aber das müsste irgendwie mit dem Shortcut gemacht werden, damit man den Member auf verschiedenen Seiten auch anders darstellen könnte; etwa so:  [pirate id=“1031″ style="card"] oder [pirate id=“1031″ style="list"]
Das wäre vielleicht auch eine Idee für die Darstellung der Crews. Momentan muss man einen Style
definieren, der dann auf jeder Seite verwendet würde; will man die gleiche Crew nochmal in anderer Form anzeigen, müsste man die Crew nochmals anlegen.

**Comment by xwolfde** [comment]
ist in der neuen version drin
